title: Bob Somers
email: bob@bobsomers.com
description: >
  Maker of things in the California bay area. Interested in far too many things
  with the free time for none of them.
baseurl: ""
url: "https://bobsomers.github.io"
twitter_username: bobsomers
github_username: bobsomers
linkedin_username: bobsomers

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
