title: Bob Somers
email: bob@bobsomers.com
description: >
  Bob Somers is a maker of things in the California bay area.
baseurl: ""
url: "https://bobsomers.github.io"
twitter_username: bobsomers
github_username: bobsomers
linkedin_username: bobsomers

markdown: kramdown
theme: minima
